### ISSUE TITLE
Use the median instead of the mean for recall costs and learn cost

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-optimizer#107]
```
            recall_costs = recall_card_revlog.groupby(by="review_rating")[
                "review_duration"
            ].mean()
```

I suggest replacing the mean with the median here, as the median is not sensitive to outliers. Relevant problem: https://forums.ankiweb.net/t/clarify-what-optimal-retention-means/42803/50?u=expertium
This could help mitigate such problems when, for example, the user went away to make dinner and, as a result, the review time ended up being orders of magnitude greater than usual, skewing the mean. And don't forget to modify how the learn cost is calculated as well, the median should be used for all time costs.
Additionally, to make the estimate even more robust (granted, the median is already robust), we can remove all times >20 minutes before calculating the median, since obviously nobody spends that much time per card.

**Comment by user1823** [comment]
Additionally, we should remove all times that are _exactly_ equal to 0 before calculating the median.

The reason is same as that given in 
- https://github.com/open-spaced-repetition/fsrs-rs/issues/126

I am requesting this again because skipping the entries during median calculation needs to be done in a way different than during mean calculation.

**Comment by L-M-Sherlock** [comment]
Should we also consider this?

<img width="478" alt="image" src="https://github.com/open-spaced-repetition/fsrs-optimizer/assets/32575846/6c2059ec-fe1d-4206-b037-04c9ed3ac255">

**Comment by user1823** [comment]
> Should we also consider this?

If I understand this function correctly, the recorded answer times would never be greater than this setting. So, do we need to consider it?

**Comment by L-M-Sherlock** [comment]
> If I understand this function correctly, the recorded answer times would never be greater than this setting. So, do we need to consider it?

I mean, if the values reach this limit, should we use them?

**Comment by user1823** [comment]
During calculation of the median, the exact values of the lowest and highest values don't matter. So, I don't think that we need to remove the entries equal to the maximum limit.

You might think that is contradictory to Expertium's suggestion of excluding answer times > 20 min. But, in that case, we are dealing with a specific situation where the user has set the maximum answer time to an unreasonably high value.

**Comment by Expertium** [comment]
I agree that all times equal to zero should be removed. As for "Maximum answer seconds", I think it's fine to keep capped values.

**Comment by Expertium** [comment]
@L-M-Sherlock just a reminder

**Comment by L-M-Sherlock** [comment]
I have checked the code which need to update today, and found that it's a little harder than my initial vision. The hardest part is the `forget_cost`.

https://github.com/open-spaced-repetition/fsrs-optimizer/blob/17d6aef313a6306b96e35a4c38c394a9d2c6be50/src/fsrs_optimizer/fsrs_optimizer.py#L1210-L1215

I will re-design this part when I have more available time.
