### ISSUE TITLE
[Feature request] Further improving the estimation of reviews times for calculating minimum recommended retention

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-optimizer#116]
While using the median (+filter) solved the problem with outliers, there is still a problem: what if the user doesn't have a lot of reviews? The fewer reviews he has, the less accurate the estimation of median review time will be.
Here's my idea:
1) Calculate the median review times per each button (+time per a new card) across all 20k collections, and save these numbers. They will be kind of like default parameters.
2) When running the simulation (for "Compute minimum recommended retention"), instead of using the median review time, use a "smoothed" medain review time:
![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/83031600/8f9b787d-4be5-424d-92c3-40a1e43151f1)
Here `n_reviews` is the number of times user pressed this particular button, `t_user` is the median time per button estimated from the user's data, and `t_default` is the default median time, estimated from 20k collections. 50 is a constant that determines how quickly the "smooth" value transitions from the default value to the actual value which is estimated from the user's data.

Example: suppose the user pressed this button 5 times, his estimated median time is 10 seconds, and the default is 7 seconds. Then the "smooth" time will be (5 / (50 + 5)) * 10 + (1 - (5 / (50 + 5))) * 7 = 7.27. Now, let's say the median stayed the same while the number of reviews increased to 500. (500 / (50 + 500)) * 10 + (1 - (500 / (50 + 500))) * 7 = 9.73. We need to store 5 `n_reviews` values: 4 for each button + 1 for new cards. We also need to store 5 default median values.

The key idea is that when the number of times the user presses a button is very small, the estimate is not very accurate, and we should rely more on the default time, which we know is accurate. So we use a "smooth" estimate that is equal to the default time when `n_reviews` is 0 and approaches the real time of this user as `n_reviews` increases. This way, when a user has very few reviews, the simulation will rely mostly on the default values, and when the user has a lot of reviews, the simulation will rely mostly on his own review time values. As a result, users with a small number of reviews will notice that the output of "Compute minimum recommended retention" varies less now. A weighted average of two medians is a bit unorthodox, but I don't see any issues with it.

**Comment by Expertium** [comment]
Oh, I didn't know. I suppose you're not planning to implement my idea then?

**Comment by L-M-Sherlock** [comment]
I haven't included the time field in my local dataset. And it also requires to store the review state. So it won't be implemented soon.

**Comment by Expertium** [comment]
Btw, if we're doing this for review times, then we need to do this for `first_rating_prob` and `first_rating_prob` as well. Same idea. Calculate probabilities for each user, then take the median of 20k datapoints, then use the same idea with smoothing.

**Comment by L-M-Sherlock** [comment]
> Btw, if we're doing this for review times, then we need to do this for `first_rating_prob` and `first_rating_prob` as well.

I think median doesn't suit this case because probability has explicit bounds: [0, 1]. Mean is more suitable.

**Comment by Expertium** [comment]
It would be a bit weird to use mean for some things and median for others, but ok.

**Comment by L-M-Sherlock** [comment]
> It would be a bit weird to use mean for some things and median for others, but ok.

Another problem of using median in prob is the sum of medians of prob is not one.

**Comment by Expertium** [comment]
I don't know what you mean.

**Comment by L-M-Sherlock** [comment]
> I don't know what you mean.


First rating prob mean: [0.256, 0.084, 0.482, 0.178]
Review rating prob mean: [0.224, 0.631, 0.145]
First rating prob median: [0.224, 0.021, 0.476, 0.085]
Review rating prob median: [0.133, 0.703, 0.038]

sum([0.256, 0.084, 0.482, 0.177]) is 1, but sum([0.224, 0.021, 0.476, 0.085]) is 0.806.

**Comment by Expertium** [comment]
Ah, I see. Btw, how many collections are these based on?

**Comment by L-M-Sherlock** [comment]
> Ah, I see. Btw, how many collections are these based on?

19822 collections.

**Comment by Expertium** [comment]
Actually, now that I think about it, we can't smooth probabilities the same way as review times, since we can't ensure that smoothed probabilities add up to 1. So forget about it, let's only use smoothing for review times.

**Comment by Expertium** [comment]
Forget what I said above. It's possible, as long as:
1) Mean (default) probabilities add up to 1
2) Measured probabilities for this particular user add up to 1
3) We use the same smoothing value for all 4 numbers

I just tried it in Excel with random numbers, and yes, it works.
