### ISSUE TITLE
Q: Effect of review_duration column on weights

### ISSUE THREAD

**Issue by joshdavham** [open-spaced-repetition/fsrs-optimizer#118]
I've been experimenting a bit with the optimizer and noticed that I get the same weights regardless of whether I include the review_duration column in my revlog file.

My question: does review_duration have any effect on the resulting optimal weights? Or does it only affect requestRetention?

I'm asking this in part because I'm building some software with FSRS and am trying to figure out whether I should be including review duration in my revlogs.

Thanks!

**Comment by Expertium** [comment]
FSRS only needs interval lengths and grades. Review duration is used for calculating optimal retention
