### ISSUE TITLE
`optimizer.create_time_series` raises Exception

### ISSUE THREAD

**Issue by YukiNagat0** [open-spaced-repetition/fsrs-optimizer#125]
On last two version of `fsrs-optimizer` (5.0.2 and 5.0.1; 5.0.0 worked fine, if I remember correctly) `optimizer.create_time_series` fails to generate `time_series` in case where user _**only uses 1 (Again) and 3 (Good) buttons for reviews**_ with following traceback:

![image](https://github.com/user-attachments/assets/62e2f6ce-fde8-449a-be11-686a83b9f5d9)

How to reproduce:

1. Download Test deck (unzip, get `fsrs4anki_Test.apkg` inside unzipped folder).
[fsrs4anki_Test.zip](https://github.com/user-attachments/files/16396821/fsrs4anki_Test.zip)
2. Run [`fsrs4anki_optimizer.ipynb`](https://github.com/open-spaced-repetition/fsrs4anki/blob/main/fsrs4anki_optimizer.ipynb) (with `%pip install -q fsrs_optimizer==5.0.2` or `%pip install -q fsrs_optimizer==5.0.1` and `timezone = 'Turkey'` if relevant)

**Comment by YukiNagat0** [comment]
Also, please, check if this bug is present in the Rust version.

**Comment by L-M-Sherlock** [comment]
The patch could solve the problem. But the number of your review logs is too less. So the optimizer still cannot optimize the parameters for you.
