### ISSUE TITLE
how to input data from obsidian-spaced-repetition-recall, ob-revlog.csv, into optimizer 

### ISSUE THREAD

**Issue by dryezl** [open-spaced-repetition/fsrs-optimizer#13]
I tried to input the data from [obsidian-spaced-repetition-recall](https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall), ob-revlog.csv, into optimizer in the colab. I could not find the right method for the data, ob-revlog.csv.

**Comment by L-M-Sherlock** [comment]
Could you share the ob-revlog.csv with me? I haven't implement the method because I don't have sample to test it.

**Comment by L-M-Sherlock** [comment]
@Newdea 表头好像不太对。应该是 card_id, review_time, review_rating, review_state, review_duration 才对。

**Comment by dryezl** [comment]
可能只是表头生成出问题的。数据按照分隔符(，)还是有五行的。

**Comment by Newdea** [comment]
> [ob_revlog.csv](https://github.com/open-spaced-repetition/fsrs-optimizer/files/12241545/ob_revlog.csv) Yes, this is my data. Thanks for your help.

这个表格是更新插件前的旧表，需要更新到最新的插件，把旧表删除，再复习的时候就按新表头保存了

**Comment by Newdea** [comment]
我晚上看下，可能是个bug

**Comment by Newdea** [comment]
问题已经修复了，现在可以正常输出到日志文件了

https://github.com/open-spaced-repetition/obsidian-spaced-repetition-recall/releases/tag/1.10.1.6

**Comment by dryezl** [comment]
[ob_revlog.csv](https://github.com/open-spaced-repetition/fsrs-optimizer/files/12268447/ob_revlog.csv)
这是新生成的数据文件，表头是没有问题的。
谢谢@Newdea

**Comment by L-M-Sherlock** [comment]
<img width="474" alt="image" src="https://github.com/open-spaced-repetition/fsrs-optimizer/assets/32575846/731a99ab-5e78-475b-a07e-58327eab4024">

@Newdea, 感觉有点奇怪，为什么每张卡片的第一次学习的 review_state 都是 2，不是 0？

**Comment by Newdea** [comment]
他已经复习过多次，而之前的数据没有记录上

**Comment by L-M-Sherlock** [comment]
好的

**Comment by YIRU69** [comment]
所以到底怎么才能得到优化后的参数呢？

**Comment by L-M-Sherlock** [comment]
目前数据不足，还无法测试。

**Comment by L-M-Sherlock** [comment]
我先加入这个 feature 支持吧。

**Comment by L-M-Sherlock** [comment]
先装一下 fsrs-optimizer
```
python -m pip install fsrs-optimizer
```
然后在你 ob_revlog.csv 的文件目录下，运行下面这个命令

```
python -m fsrs_optimizer "ob_revlog.csv"
```

就可以优化了。

**Comment by dryezl** [comment]
我在[google colab](
https://colab.research.google.com/drive/1_bUXeCZ1QHcINlqZqhV0i9MJVjjodP2b?usp=drive_link)里面尝试上述方法，运行出错的。
输入文件是[ob_revlog.csv](https://github.com/open-spaced-repetition/fsrs-optimizer/files/12268447/ob_revlog.csv)
具体报错如下：
The defaults will switch to whatever you entered last.

Timezone list: https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568
input used timezone : Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/fsrs_optimizer/__main__.py", line 177, in <module>
    process(filename)
  File "/usr/local/lib/python3.10/dist-packages/fsrs_optimizer/__main__.py", line 52, in process
    remembered_fallback_prompt("timezone", "used timezone")
  File "/usr/local/lib/python3.10/dist-packages/fsrs_optimizer/__main__.py", line 46, in remembered_fallback_prompt
    remembered_fallbacks[key] = prompt(f"input {pretty}", remembered_fallbacks[key])
  File "/usr/local/lib/python3.10/dist-packages/fsrs_optimizer/__main__.py", line 16, in prompt
    response = input(f"{msg} {default}: ")
EOFError: EOF when reading a line
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-8-ce321632b8f3> in <cell line: 1>()
----> 1 get_ipython().run_cell_magic('sh', '', 'python -m fsrs_optimizer "ob_revlog.csv"\n')

4 frames
/usr/local/lib/python3.10/dist-packages/google/colab/_shell.py in run_cell_magic(self, magic_name, line, cell)
    332     if line and not cell:
    333       cell = ' '
--> 334     return super().run_cell_magic(magic_name, line, cell)
    335 
    336 

/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2471             with self.builtin_trap:
   2472                 args = (magic_arg_s, cell)
-> 2473                 result = fn(*args, **kwargs)
   2474             return result
   2475 

/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py in named_script_magic(line, cell)
    140             else:
    141                 line = script
--> 142             return self.shebang(line, cell)
    143 
    144         # write a basic docstring:

<decorator-gen-103> in shebang(self, line, cell)

/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

/usr/local/lib/python3.10/dist-packages/IPython/core/magics/script.py in shebang(self, line, cell)
    243             sys.stderr.flush()
    244         if args.raise_error and p.returncode!=0:
--> 245             raise CalledProcessError(p.returncode, cell, output=out, stderr=err)
    246 
    247     def _run_script(self, p, cell, to_close):

CalledProcessError: Command 'b'python -m fsrs_optimizer "ob_revlog.csv"\n'' returned non-zero exit status 1.

**Comment by L-M-Sherlock** [comment]
优化器使用过程中需要通过交互输入参数

**Comment by L-M-Sherlock** [comment]
![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/32575846/554cbe09-99aa-4630-8ccb-7173589aa74b)

**Comment by dryezl** [comment]
加上参数"-y"仍然报错的，可能是输入文件的问题。
[运行代码](
https://colab.research.google.com/drive/1_bUXeCZ1QHcINlqZqhV0i9MJVjjodP2b?usp=drive_link)
请问你可不可以帮忙看一下这个文件[ob_revlog.csv](https://github.com/open-spaced-repetition/fsrs-optimizer/files/12268447/ob_revlog.csv)为什么会出错呢?

**Comment by L-M-Sherlock** [comment]
我在本地测试了一下，发现只有一条有效数据，数据不够优化，就报错了。

**Comment by dryezl** [comment]
谢谢。请问数据是否有效的判断标准是？

**Comment by L-M-Sherlock** [comment]
每张卡片的复习数据的第一条的review_state是否为0

**Comment by L-M-Sherlock** [comment]
> 不好意思，加一个问题。请问一般需要多少条有效数据才能进行优化呢？

一般来说至少需要 100 条

**Comment by dryezl** [comment]
谢谢。
