### ISSUE TITLE
FSRS-5 优化器，优化参数时发生报错：“error Columns not found: 1, 2, 3, 4”

### ISSUE THREAD

**Issue by hihaojie** [open-spaced-repetition/fsrs-optimizer#134]
大佬，我的 CSV 用 FSRS-4 优化器可以正常优化，用 FSRS-5 优化器会报错：“error Columns not found: 1, 2, 3, 4”

![image](https://github.com/user-attachments/assets/3d4a2701-f66c-4237-9d89-3b3c5aefab24)

训练用的 CSV 文件如下：
[revlog2024-0501.csv](https://github.com/user-attachments/files/16829377/revlog2024-0501.csv)

**Comment by L-M-Sherlock** [comment]
`review_duration` 全是 0。这个输入不合法。建议把这一列删掉。

**Comment by L-M-Sherlock** [comment]
这个插件的作者是谁？可以联系他一下吗？如果 review_duration 没记录，就不要导出这一列了。

**Comment by hihaojie** [comment]
> 数据导出插件的作者是谁？可以联系他一下吗？如果 review_duration 没记录，就不要导出这一列了。

按照您说的，我把这一项移除后可以正常训练了。
这个插件作者不再维护了😭，插件也下架了。我拿着旧插件勉强在用
原插件项目链接：https://github.com/mdzz2048/siyuan-plugin-export-revlog

**Comment by L-M-Sherlock** [comment]
好吧，我看看我有空能不能也维护一个。这个 issue 我就先关了。

**Comment by L-M-Sherlock** [comment]
> 插件也下架了

问一下，插件怎么上架？
