### ISSUE TITLE
Change l1 = np.abs(stability - init_s0) / 16

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-optimizer#144]
Here's a graph that shows how w[3] is distributed
![image](https://github.com/user-attachments/assets/b6ad5aa9-135c-4ed8-8f41-a7bda7197722)
 
As you can see, there is a large peak at around 15.6, which is the default value. This is likely because of this line of code:
`                l1 = np.abs(stability - init_s0) / 16 if not self.float_delta_t else 0`

I recommend you to try different values instead of 16, like 32 and 64, and see if it results in a more natural-looking graph

I also recommend to try using relative difference instead
` l1 = np.abs(stability - init_s0)/init_s0`

**Comment by L-M-Sherlock** [comment]
But it doesn't happen in w[0], w[1] and w[2]. The reason why w[3] is affected is thousands of users didn't press easy on new cards.

**Comment by Expertium** [comment]
![w 3](https://github.com/user-attachments/assets/92ef53b2-8515-4817-a3f8-3d957091a53c)
I tried `l1 = np.abs(stability - init_s0) / (2 *  init_s0)`, but the peak is still there
