### ISSUE TITLE
[Feature request] A way to extrapolate values of S0 without curve_fit

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-optimizer#19]
Currently we are using curve_fit to extrapolate values of S0, which often leads to values that are too small or too big. Here is what I propose:
Again = Hard^2/Good
Hard = sqrt(Again * Good)
Good = sqrt(Hard * Easy)
Easy = Good^2/Hard
Basically, we assume that Hard and Good can be calculated as geometric averages of their neighboring values, and from these formulas we can derive formulas for Again and Easy as well. Note that this should be used **only** for extrapolation, when the number of reviews for a particular grade is 0.

**Comment by L-M-Sherlock** [comment]
Good idea. Let's discuss all the possible situations for the first review data.

Category One: Data includes all four ratings - 'again,' 'hard,' 'good,' and 'easy.'
Category Two: Data has only three types of ratings.
Category Three: Data has only two types of ratings.
Category Four: Data has only one type of rating.

Category One is not part of this issue's discussion. For Category Four, the current method sets the same starting stability value for all four ratings.

For Category Two, your suggested method can solve it perfectly. Lastly, the issue might be with Category Three. If both 'hard' and 'good' ratings are missing, your method might not work.

**Comment by Expertium** [comment]
> For Case One, the alternative method is to set `hard` to `good`^2/`easy`. Then, apply `again` = `hard`^2/`good`
> 
> For Case Three, we can set `good` to `hard`^2 / `again`, Then apply `easy` = `good`^2/`hard`.

I thought about this as well, seems like a good idea. For Case Two I don't know what to do either. I'll think about it.
As for Category Four, that one is very tricky. Here's my idea: take the default values and scale them so that one of them matches the only available rating, preserving their ratios. Example: only "Good" is available, and the value for it is 1.5. The default value for Good is 1. That means that our valeus is 1.5 times greater than default, so we multiply all default values by 1.5.

**Comment by L-M-Sherlock** [comment]
Oh. I figure it out.

Let a, b, c and d indicate initial stability for again, hard, good and easy. Here are some equations:

1. a = b^2/c
2. b = (ab)^(1/2)
3. c = (bd)^(1/2)
4. d = c^2/b

Then we can represent b and c with a and d:

1. b = a^(2/3)*d^(1/3)
1. c = a^(1/3)*d^(2/3)

**Comment by L-M-Sherlock** [comment]
I find a bad case:

0.16 for hard
2.4 for good

With Easy = Good^2/Hard, the initial stability for easy should be 36. Do you think it is too large?

**Comment by Expertium** [comment]
Hmmm. We could take this a step further.
d = (c^w1)*(b^w2), where w1 and w2 are optimized on large bodies of data. In other words, we could find the best parameters for extrapolation by trying different values on different collections.

**Comment by Expertium** [comment]
So I did the math in Excel since I wrote down values of S0 anyway to find the best values, and I removed those datapoints where I replaced S0(Easy) with 5.8 or something else.
For minimization I used [symmetric MAPE](https://en.wikipedia.org/wiki/Symmetric_mean_absolute_percentage_error).
So here are the values: w1=-0.869, w2=1.937
S0(Easy)=(S0(Hard)^w1) * (S0(Good)^w2)

**Comment by L-M-Sherlock** [comment]
We should control w1 + w2 = 2.

**Comment by L-M-Sherlock** [comment]
I think we should be more conservative here. Because when we need to extrapolate value for easy, there is zero review for easy. If the interval is too large, the user would not press easy any more.
