### ISSUE TITLE
[BUG] Loosen the clamping for w[10] and w[8]

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs-optimizer#28]
This is a pretty minor thing so I won't make a new issue for it, but @L-M-Sherlock, I suggest changing the clampings for w[10] and w[8] (the parameters in `new_s = state[:,0] * (1 + torch.exp(self.w[8]) * (11 - new_d) * torch.pow(state[:,0], -self.w[9]) * (torch.exp((1 - r) * self.w[10]) - 1) * hard_penalty * easy_bonus)`) from 
```
w[10] = w[10].clamp(0.01, 1.5)
w[8] = w[8].clamp(0, 2)
```
 to
 ```
w[10] = w[10].clamp(0.01, 2.5)
w[8] = w[8].clamp(0, 3)
```
I noticed that they both maxed out for one of my decks.

_Originally posted by @Expertium in https://github.com/open-spaced-repetition/fsrs4anki/issues/351#issuecomment-1679355584_

**Comment by L-M-Sherlock** [comment]
@Expertium, could you share your parameters in the affected decks?

According to the formula, these changings would enlarge your intervals.

**Comment by Expertium** [comment]
[1.06, 1.49, 10.21, 71.52, 3.837, 0.3496, 1.0903, 0.1844, 2.0, 0.1, 1.5, 2.4671, 0.0822, 0.516, 1.7318, 0.1453, 3.6116]

This is a deck with very easy material, so in a way it's an outlier.

**Comment by L-M-Sherlock** [comment]
By the way, I develop a previewer for FSRS: https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_previewer

<img width="1258" alt="image" src="https://github.com/open-spaced-repetition/fsrs-optimizer/assets/32575846/b81ccd0f-5808-43e5-a629-7bb8a362bdd0">

The results show that the interval increases very quickly.

**Comment by Expertium** [comment]
I don't think that loosening the clampings on these parameters will have any impact on most decks, it will only affect very easy decks. So if you are worried that this will negatively affect a lot of users, I don't think it will.

**Comment by L-M-Sherlock** [comment]
OK. I will loosen the clampings in the next patch.
