### ISSUE TITLE
[Feature Request] Loosen the clampings for w[9]

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-optimizer#30]
**Is your feature request related to a problem? Please describe.**
I checked my parameters again and noticed that w[9] is 0.1 for some easy decks.

**Describe the solution you'd like**
I suggest changing the clamping to `w[9] = w[9].clamp(0.025, 0.8)`

**Comment by L-M-Sherlock** [comment]
According to https://supermemo.guru/wiki/Stabilization_decay,  w[9] is usually in the range of [0.2, 0.8]. I have loosened it to [0.1, 0.8].

**Comment by Expertium** [comment]
Supermemo formulas aren't exactly the same as ours.

**Comment by L-M-Sherlock** [comment]
At least for stabilization decay, FSRS and SM are the same. And for easy cards, I'm afraid it's due to the underestimation of initial stability.

**Comment by Expertium** [comment]
I just checked parameters of another user, he also has the same issue with w[9].
[0.1358, 0.5044, 18.4034, 18.4034, 4.8368, 1.1219, 0.8531, 0.0, 1.3932, **0.1**, 0.8975, 2.0978, 0.1428, 0.3228, 1.3624, 0.2382, 2.7056]

**Comment by L-M-Sherlock** [comment]
My main worry is if w[9] is too small, the long-term interval will be very large, which could scare new users.
