### ISSUE TITLE
Training data is inadequate.

### ISSUE THREAD

**Issue by mdzz2048** [open-spaced-repetition/fsrs-optimizer#36]
根据叶哥在 [这里](https://github.com/siyuan-note/siyuan/issues/8594#issuecomment-1656016186) 的提示，参考该库的标准导出了思源的  [复习数据](https://github.com/open-spaced-repetition/fsrs-optimizer/files/12558259/202308.msgpack.csv)

使用 FSRS-optimizer 报错如下

![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/86549958/8fb3e661-2bdc-4d48-bdcf-b99a7da3d047)

[这个 issue](https://github.com/open-spaced-repetition/fsrs-optimizer/issues/13) 里提到”每张卡片的复习数据的第一条的review_state为 0“的有效数据需要大于 100 条，这个文件里的数据应该是达到了这个标准。

![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/86549958/603c62cb-5907-44cf-9770-ff5f13f98f06)

请问我是否哪一步做错了？应该如何解决这个问题？

**Comment by L-M-Sherlock** [comment]
review_time 必须是毫秒而非秒，否则数据会被过滤掉。

**Comment by mdzz2048** [comment]
抱歉，之前没注意，修改后运行报错
![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/86549958/baf7e353-9ced-48b1-abcf-79b3ef7031cc)

**Comment by L-M-Sherlock** [comment]
正在定位bug，请稍等待

**Comment by L-M-Sherlock** [comment]
修复了，更新一下包试试。

**Comment by mdzz2048** [comment]
ok 了，感谢叶哥！

![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/86549958/621ac438-ddfa-457a-b82d-9b665f7f6001)
