### ISSUE TITLE
[Question] Explain how the optimizer calculates retention that minimizes review times

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-optimizer#38]
That's the section of the optimizer that I am least familiar with. I would like to understand it better. I was looking at the code, and the only part that I clearly understand is this:
```
                    exp_times = (
                        p_recalls * recall_times + (1.0 - p_recalls) * forget_times
                    )
```
Expected time equals the probability of a pass (Hard/Good/Easy) multiplied by the amount of time user spends on such reviews plus the probability of a failure (Again) multiplied by the amount of time user spends on such reviews. 
However, the rest of the code is magic to me, and I don't understand what difficulty has to do with anything there. I would greatly appreciate a detailed explanation of what each piece code does, ideally both a general, abstract overview (aka explain the key principles) and a more in-depth explanation of each chunk of code.

**Comment by L-M-Sherlock** [comment]
Please see my paper. The mechanism of this part has been described in Section 4 OPTIMAL SCHEDULING:

<img width="1045" alt="image" src="https://github.com/open-spaced-repetition/fsrs-optimizer/assets/32575846/9c146577-07c1-430a-a38a-93065d2bec75">

source: www.maimemo.com/paper/

**Comment by L-M-Sherlock** [comment]
By the way, I plan to use a brand new way to find the optimal retention in FSRS Optimizer. It has been implemented in https://github.com/open-spaced-repetition/fsrs-rs

The main idea of the new method is to simulate the review process of user with different retention and select the retention which maximize the estimated total knowledge.

**Comment by Expertium** [comment]
> The main idea of the new method is to simulate the review process of user with different retention and select the retention which maximize the estimated total knowledge.

Can you explain how that one works then? The way I see it, it will just suggested the max. retention every time, since that's what maximizes total knowledge. Unless you mean total knowledge acquired per unit of time.

**Comment by L-M-Sherlock** [comment]
In the simulation, the time to learn per day is fixed. If the retention is too high, the user will have no time to learn new cards.

**Comment by Expertium** [comment]
That's not ver yeasy for me to understand, but thank you.
Unrelated, but have you compared the speeds of the Rust-based optimizer and Python-based optimizer? I would assume that Rust version is faster.

**Comment by L-M-Sherlock** [comment]
I haven't compared the speeds. Because Rust-based optimizer hasn't implemented the splits of dataset.

**Comment by Expertium** [comment]
Also, how do you know whether the new method is better?
With the algorithm itself, finding out whether a change is good or bad is very straightforward - just run both on the same dataset and check the RMSE. We have "ground truth" - the actual repetition history. But how do you assess which method of finding optimal retention is better?

**Comment by L-M-Sherlock** [comment]
The old method didn't support decimal difficulty, so it's imprecise. And it also assumed the user only press `good` and `again`.

**Comment by Expertium** [comment]
![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/83031600/d4213235-fcd3-4c1c-9b8a-cb790f57e73f)
So I was looking at the code, and this raises 2 questions:
1) If I understand it correctly, does it mean that in the simulator "Again" can only happen during the first review, and cannot happen during later reviews? `review_rating_prob` only has 3 values.
2) Wouldn't it be better to estimate these probabilities from the user's actual review history?

**Comment by L-M-Sherlock** [comment]
https://github.com/open-spaced-repetition/fsrs-optimizer/blob/3583fd2e760b78bd1b4406257d363bb0234f9349/src/fsrs_optimizer/fsrs_simulator.py#L101-L103

The forget cards' ratings must be `again`, so we don't need to sample for them. The code only sample rating from`hard`, `good` and `easy` for those recalled cards.

https://github.com/open-spaced-repetition/fsrs-optimizer/blob/3583fd2e760b78bd1b4406257d363bb0234f9349/src/fsrs_optimizer/fsrs_optimizer.py#L515-L532

Here I have estimated these probabilities from the user's actual review history.

**Comment by Expertium** [comment]
Thank you. One more question: does the simulator use the same value of answer time (`recall_cost`) for Hard, Good and Easy? Wouldn't it be more precise to use 3 different values for three passing grades?

**Comment by L-M-Sherlock** [comment]
The current simulator uses the same value. You can open an issue for this feature request.
