### ISSUE TITLE
[Bug] Can't use absolute path as arg

### ISSUE THREAD

**Issue by tkngaejcpi** [open-spaced-repetition/fsrs-optimizer#43]
When I exec `python -m fsrs_optimizer ~/Desktop/foo.apkg`, the program asked for some basic config at first, then error was thrown:

```
[Errno 2] No such file or directory: '..//home/foo/Desktop/foo.apkg'
Failed to process /home/foo/Desktop/foo.apkg
```

After I copied the file into the same folder, and exec `python -m fsrs_optmizer ./foo.apkg`, everything just worked normally.

If this is a feature, it makes more sense to raise the error at the beginning.

Otherwise, it must be just some trivial problems of path handling. If you want, I can create a PR of it.

**Comment by L-M-Sherlock** [comment]
PR is welcome.
