### ISSUE TITLE
[BUG] 'Optimizer' object has no attribute 'w'

### ISSUE THREAD

**Issue by HominidaeBlaze** [open-spaced-repetition/fsrs-optimizer#45]
Followed the steps in the tutorial but while training the FSRS parameters I got this message repeatedly.

**Comment by Expertium** [comment]
Please provide more details.
1) Which options did you select when exporting your Anki collection?
![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/83031600/af1ad127-6c29-4657-ab1e-008b32044fea)
2) How did you change this part of the optimizer code?
![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/83031600/4b229937-7677-44f6-9d4d-88d06ffbb2f0)
3) Wat did you press to run the optimizer? You should either press Ctrl + F9 or Runtime -> Run all.
