### ISSUE TITLE
[Feature request] Improve post-lapse stability analysis

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-optimizer#55]
I really like the new post-lapse stability analysis feature, and I think we can improve the post-lapse stability (PLS) formula if we analyze how post-lapse stability is related to D and R as well.
![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/83031600/5160edca-84ef-4fc5-9b4f-30b4277d44d3)
In other words, the two new graphs should have D and predicted R (at the time of the review) on the x axis and PLS on the y axis, with both true PLS (dots) and predicted PLS (curve), of course. This will help us determine how exactly PLS depends on D and R and whether the current formals provide a good fit. In the future, a similar approach can be used for the main formula as well, just with three different graphs for each grade. For now, the idea is to analyze how PLS depends on the three components of memory.

**Comment by Expertium** [comment]
@L-M-Sherlock, thank you for making a Google colab notebook! Please, implement my suggestion above as well.

**Comment by Expertium** [comment]
I noticed something, I think Sherlock mentioned a similar phenomenon before.
I replaced the function for calculating PLS with a different one, and while RMSE for "Again" got better, the overall RMSE got worse. I have no idea how to explain this.
![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/83031600/8bc8fb90-c1ef-48ec-a349-91b767fd3ef7)

**Comment by L-M-Sherlock** [comment]
I update the test version for notebook: https://github.com/open-spaced-repetition/fsrs4anki/blob/test/fsrs4anki_optimizer_test.ipynb

![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/32575846/081974aa-8f1a-4f5b-a4aa-54c48cdbf3ca)

You can set the group_key to `last_s_bin`, `last_d_bin` and `last_r_bin`.

**Comment by Expertium** [comment]
It's not exactly what I wanted, I wanted 3 charts just like the one you originally made, but thank you.

**Comment by Expertium** [comment]
@L-M-Sherlock I have another request. It seems that no matter how I improve the formula for PLS, it somehow makes the overall RMSE worse, which means that we need to analyze the main formula the same way. Please, add 3 more graphs:
1) new S as a function of previous S
2) new S as a function of last R
3) new S as a function of last D
And remove grades 2 and 4, leaving only 3. In other words, only reviews when user pressed "Good" should be used for analysis, to simplify things.

**Comment by L-M-Sherlock** [comment]
> Please, add 3 more graphs:
> 
> 1. new S as a function of previous S
> 2. new S as a function of last R
> 3. new S as a function of last D

Done:

![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/32575846/be711b90-743d-4a41-8a35-6fb65fa13298)

![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/32575846/87eaf079-a50e-43be-b39e-91996b7875e0)

![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/32575846/70d8f8a6-00d7-4a97-9dab-0847fd0ac7dc)

**Comment by Expertium** [comment]
Is there no way to speed this code up? It takes more time than any other part of the code related to plotting graphs.
```
ns_dataset["last_state"] = ns_dataset.progress_apply(
    lambda x: my_collection.predict(
        ",".join(x["t_history"].split(",")[:-1]),
        ",".join(x["r_history"].split(",")[:-1]),
    ),
    axis=1,
)
```

**Comment by Expertium** [comment]
Interestingly, S as function of previous S provides practically a perfect fit (log coordinates):
![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/83031600/21576c15-3208-447b-b02c-49f54550d98f)

**Comment by L-M-Sherlock** [comment]
> Is there no way to speed this code up? It takes more time than any other part of the code related to plotting graphs.

Done in https://github.com/open-spaced-repetition/fsrs4anki/commit/a5ae9f187c687231e41ebce181580c3cba4efe58

**Comment by Expertium** [comment]
Thank you. A few more suggestions, nothing urgent:
1) Add RMSE between true S and predicted S (and do that for PLS too), like this:
```
rmse = mean_squared_error(pls_df_group["true_s"], pls_df_group["predicted_s"], sample_weight=pls_df_group["total_count"], squared=False)
print(f'RMSE={rmse:.2f}')
```
2) Analyzing new S as a function of preivous S is more convenient when both are in log coordinates, so add this:
```
    if group_key == "last_s_bin":
        ax1.set_ylim(0.1, ns_df_group["predicted_s"].max() * 1.1)
        ax1.set_xscale("log")
        ax1.set_yscale("log")
```

**Comment by Expertium** [comment]
By the way, you may be interested in these charts for my collection
![image](https://github.com/open-spaced-repetition/fsrs-optimizer/assets/83031600/dff412a2-3aa7-4317-b672-45b658b1d2da)
It seems that the main formula provides a good fit overall, but the formula for PLS tends to overestimate S

**Comment by L-M-Sherlock** [comment]
> Thank you. A few more suggestions, nothing urgent:

Done in: https://github.com/open-spaced-repetition/fsrs4anki/commit/7cb2bb4ccc4d26d27f945190226f460081645ab7

**Comment by Expertium** [comment]
Nice. Once you have enough free time, please test my idea regarding PLS: https://github.com/open-spaced-repetition/fsrs4anki/issues/461#issuecomment-1773870958
