### ISSUE TITLE
See if this code could be used to speed up finding optimal retention

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-optimizer#60]
I copied sicpy.optimize.brent, removed some stuff and hard-coded the 0.75-0.95 boundary into it. You can read about the Brent method [on the Wikipedia](https://en.wikipedia.org/wiki/Brent%27s_method) and also you can read [the scipy documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.brent.html). It says "The minimizer x will not necessarily satisfy xa <= x <= xb.", but again, I hard-coded my implementation to always return values between 0.75 and 0.95.
If time(loss(x)) >> time(math), in other words, if the amount of time required to calculate the value of the loss function is much greater than the amount of time required to do the math, then Brent is faster due to the fact that it calls the loss function less often.
If time(loss(x)) << time(math), in other words, if the value of the loss function can be calculated extremely quickly, then Brent is slower due to doing all of the extra math.
In the example in the .py file below, Brent called the loss function 7 times vs 16 times for the naive loop.

[Brent minimization.zip](https://github.com/open-spaced-repetition/fsrs-optimizer/files/13339907/Brent.minimization.zip)

This was originally intended for best fit D, but it works just as well with any function that is continuous within some interval [a, b] and has a minimum. I hardcoded a and b to be 0.75 and 0.95.

**Comment by L-M-Sherlock** [comment]
Yeah, the code is faster than the native one. With the default configuration, the native one takes 11 seconds, while the new one only takes 5 seconds. But their results are inconsistent. I will do more research here.

**Comment by L-M-Sherlock** [comment]
optimal retentino=0.8130391708581008                                                                                                                                                                        
Time (naive)=11.2 seconds

optimal retentino=0.7943779786643673
Time (Brent)=6.2 seconds

The difference is near 0.02. It is not negligible.

**Comment by L-M-Sherlock** [comment]
OK. By the way, could you explain what `tol` means?

**Comment by Expertium** [comment]
You mean in the new method? Honestly, I don't know. It has this condition, but I don't really understand the rationale behind it.
```
    while iter < maxiter:
        tol1 = tol * np.abs(x) + mintol
        tol2 = 2.0 * tol1
        xmid = 0.5 * (a + b)
        # check for convergence
        if np.abs(x - xmid) < (tol2 - 0.5 * (b - a)):
            break
```

**Comment by Expertium** [comment]
Here's what I would recommend. First, as I mentioned, run the optimizer many times to average the values of the cost to obtain the true minimum. Then, run both the naive loop and the Brent method hundreds of time `on noisy output` and record abs(true minimum - output).
Basically, once you already know the true minimum, you can calculate the difference between the output of a minimization function and the minimum. But we don't want to run the minimization function on smoothed values, we want to run them on noisy values to see how well they can handle working with noise. Then average the errors.
In the end, you should have 100 (or however many times you want to run this) values of abs(true minimum - output), all of them will be slightly different due to noise. Then you can average them out to see which method is, on average, closer to the truth.
For example, if the average error of Brent is 0.01, that would mean that, on average, it is off from the true minimum by 0.01 when trying to estimate it from noisy output.

**Comment by L-M-Sherlock** [comment]
I update the branch. Now you can run the test via:

```
git checkout -b dev origin/Feat/speed-up-finding-optimal-retention
python ./src/fsrs_optimizer/fsrs_simulator.py
```

**Comment by Expertium** [comment]
I would prefer to save it on my PC so I can edit it easily.

**Comment by L-M-Sherlock** [comment]
You can clone the repo into your local device.

**Comment by L-M-Sherlock** [comment]
Yeah. If you install GitHub Desktop, it will be easier to checkout the branch.

**Comment by Expertium** [comment]
So first I ran this loop (with default parameters):
```
R = np.arange(0.75, 0.95, 0.001)
memorization_costs = []
for i in R:
    cost = sample(n=500, w=default_w, mid=i)
    memorization_costs.append(cost)

print(memorization_costs)
```
This took a lot of time, but it allowed me to get the true minimum.
`true_min = R[memorization_costs.index(max(memorization_costs))]`

Then I ran this loop:
naive_errors = []
```
for i in range(100):
    output = optimal_retention(w=default_w)
    naive_errors.append(np.abs(output-true_min))

print(np.mean(naive_errors))
```
I recorded the average error, then ran it again but with Brent method instead.
Here are the results:
naive_avg_error = 0.01916338972717579 (around 0.02)
brent_avg_error = 0.0076121910291120365 (less than 0.01)
`tol` was set to 0.01 for both. So Brent is faster _and_ more accurate.

**Comment by Expertium** [comment]
So how is it? Have you tested it further or are you waiting for something?

**Comment by L-M-Sherlock** [comment]
I'm evaluating the difficulty to implement it in fsrs-rs.

**Comment by Expertium** [comment]
I doubt it would be difficult to port this to Rust. I mean, it's just barebones math; neither `bracket` nor the minimization function itself rely on any external libraries that would be unavailable in Rust.
