### ISSUE TITLE
[Feature Request] Add another condition to the outlier filter

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/fsrs-optimizer#83]
I suggest the following condition: lapses≥10 AND reviews≥40.
This should filter out the worst leeches. This should be applied before optimization. Btw, I don't really know how the current filter works, perhaps there is already something similar.
@user1823 what do you think?

**Comment by user1823** [comment]
It can be useful for some users but it can be detrimental for others (especially those who are using Anki for more than 5-10 years).

> perhaps there is already something similar.

No, there isn't.

**Comment by Expertium** [comment]
Fair point. Then how about this:
leech_threshold = max(10, percentile(leeches, 0.95))
reps_threshold = max(40, percentile(reps, 0.95))
This is more adaptive. For users with young collections, the thresholds will be 10 and 40. For users with old collections, thresholds will be higher. Both the number of leeches and the number of reviews need to exceed the threshold in order for that card to be excluded from optimization.

**Comment by Expertium** [comment]
@user1823 @L-M-Sherlock maybe we should also remove "anti-leeches" - cards with no Again ratings. For example, remove cards with n(Again)=0 and n(reviews)>10. Just like leeches, they do not follow the usual memory patterns, just in a different way.

**Comment by L-M-Sherlock** [comment]
Users can filter out those cards via specific query: https://docs.ankiweb.net/searching.html#card-properties
